#! /bin/sh
# /etc/init.d/TornadoServerStart

### BEGIN INIT INFO
# Provides:          TornadoServerStart
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to start a program at boot
# Description:       A script which will allow the tornado server to run at boot
### END INIT INFO

case "$1" in
  start)
    echo "Starting Tornado server..."
    sudo python /var/www/LAVA-3DPrinter/TornadoServer.py &
    ;;
  stop)
    echo "Stopping Tornado server..."
    ;;
  *)
    echo "Usage: /etc/init.d/TornadoServerStart {start|stop}"
    exit 1
    ;;
esac

exit 0
